### PR TITLE
Add rule for dangling commas.

### PR DESCRIPTION
**Pull request by jkinkead**
I couldn't figure out how to test this, so I didn't.

### CODE REVIEW

**Comment by codeviking** [comment]
:+1:

**Comment by codeviking** [comment]
@jkinkead Since I'm all tied up want to handle post-merge version increment + publish?  I also cut a tag with every publish.

**Comment by jkinkead** [comment]
I actually have no memory of how to do this, and I don't think there's instructions?

**Comment by codeviking** [comment]
Nope, I cut an issue: https://github.com/allenai/syrup/issues/53

Simply:

Increment the version in `package.json`.

Cut a tag:
```
git tag -a v0.x.x -m v0.x.x
git push --tags
```

Publish:
```
npm publish
```

**Comment by jkinkead** [comment]
I will try this!

**Pull request merged**
